CEPCQ/CEPCQ/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls'))
]

CEPCQ/music/urls.py
from django.conf.urls import url

from . import views
app_name= 'music'

urlpatterns = [
    #/music/
    url(r'^$', views.index, name='index'),
    # /music/71/
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),



    #/music/id/fav
    url(r'^(?P<album_id>[0-9]+)/fav/$', views.fav, name='fav' )
]

CEPCQ/music/models.py
from django.db import models

class Album (models.Model):
    artista = models.CharField(max_length=250)
    titulo_album = models.CharField(max_length=250)
    genero = models.CharField(max_length=250)
    imagen = models.CharField(max_length=250)

    def __str__(self):
        return self.titulo_album + ' - ' + self.artista

class Song (models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=250)
    titulocancion = models.CharField(max_length=250)
    isFav = models.BooleanField(default=False)

    def __str__(self):
        return self.titulocancion

CEPCQ/music/views.py
from django.http import HttpResponse
from django.http import Http404
from .models import Album, Song
from django.template import loader
from django.shortcuts import render, get_object_or_404


def index(request):
    all_albums = Album.objects.all()
    '''
    html=''
    for album in all_albums:
        url='/music/'+ str(album.id) + '/'
        html += '<a href="'+url+'">'+ album.titulo_album + ' </a><br>'
    return HttpResponse(html)
    '''

    context = {'all_albums': all_albums}
    return render(request, 'music/index.html', context)


def detail(request, album_id):
    '''
    try:
        album = Album.objects.get(pk=album_id)
    except Album.DoesNotExist:
        raise Http404("Album no existe")
    return render(request, "music/detail.html", {'album': album})
    '''

    album = get_object_or_404(Album, pk=album_id)
    return render(request, "music/detail.html", {'album': album})


def fav(request, album_id):
    '''
    try:
        album = Album.objects.get(pk=album_id)
    except Album.DoesNotExist:
        raise Http404("Album no existe")
    return render(request, "music/detail.html", {'album': album})
    '''

    album = get_object_or_404(Album, pk=album_id)
    try:
        selected= album.song_set.get(pk=request.POST['song'])
    except(KeyError, Song.DoesNotExist):
        return render(request, "music/detail.html", {'album': album, 'error': "fail"})
    else:
        selected.isFav=True
        selected.save()
        return render(request, "music/detail.html", {'album': album})

CEPCQ/music/templates/music/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'music/styles.css' %}"/>

    <script src="{% static 'music/js/main.js' %}"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
        </div>
 <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums</a></li>
                <li ><a href="#"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>


{% block body %}
{% endblock %}
</body>
</html>

CEPCQ/music/templates/music/detail.html
{% extends 'music/base.html' %}


{% block title %}
    detalles
{% endblock %}

{% block body %}

        <img src="{{ album.imagen }}">
        <h1>{{ album.titulo_album }}</h1>
        <h3>{{ album.artista }}</h3>



        {% if error %}

        <p><strong>error</strong></p>

        {% endif %}

        <form action="{% url 'music:fav' album.id%}" method="post">
            {%  csrf_token %}

            {%  for song in album.song_set.all %}
            <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
                <label for="song{{ forloop.counter }}">
                {{ song.titulocancion }}
                {% if song.isFav %}

                    <img src="http://d27evk36qsa75y.cloudfront.net/impl_img/star_highlight.gif">

                {% endif %}
        <br>

                </label>
            {% endfor %}
        <input type="submit" value="Favorite">

        </form>

{% endblock %}

CEPCQ/music/templates/music/index.html
{% extends 'music/base.html' %}


{% block title %}
    albumes
{% endblock %}
{% block body %}
{% if all_albums %}

    <ul>
    <li>
        {% for album in all_albums%}


            <a href="{% url 'music:detail' album.id%}">{{ album.titulo_album }}</a><br>

        {% endfor %}

    </li>


    </ul>

    {% else %}

        <h3>vacio</h3>

    {% endif %}


{% endblock %}